allowed-duplicate-crates = [
	# Seems like tracing* is lagging a bit
	"nu-ansi-term", "regex-automata", "regex-syntax",
	# Words cannot express how much I don't care about these
	"windows-sys", "windows-targets", "windows_aarch64_gnullvm", "windows_aarch64_msvc", "windows_i686_gnu", "windows_i686_msvc", "windows_x86_64_gnu", "windows_x86_64_gnullvm", "windows_x86_64_msvc",
]
