allowed-duplicate-crates = [
	# tracing-subscriber is dragging their feet on bumping deps
	"regex-automata", "regex-syntax", "nu-ansi-term",
	# Words cannot express how much I don't care about these
	"windows-sys", "windows-targets", "windows_aarch64_gnullvm", "windows_aarch64_msvc", "windows_i686_gnu", "windows_i686_msvc", "windows_x86_64_gnu", "windows_x86_64_gnullvm", "windows_x86_64_msvc",
]
