name: Security audit
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    paths:
      - "**/Cargo.*"
      - ".github/workflows/audit.yml"
  pull_request:
    branches:
      - main

jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install rust
        id: rust-install
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: Install cargo-audit
        run: cargo install cargo-audit

      - name: Audit deps
        run: |
          cargo audit -D warnings

  nightly_compat:
    name: See if future Rust versions (or deps) will break anything
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install rust
        id: rust-install
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: clippy

      # Normally this would be where we use actions/cache, but since nightly
      # is likely to change on every run, it doesn't seem worth it

      - name: Update deps
        run: |
          cargo +${{ steps.rust-install.outputs.name }} update

      - name: Test
        env:
          RUSTFLAGS: -D warnings
        run: |
          cargo +${{ steps.rust-install.outputs.name }} test

      - name: Clippy
        run: |
          cargo +${{ steps.rust-install.outputs.name }} clippy -- -D warnings
