name: Quality Control

on:
  push:
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
            ~/.rustup
            target/
          key: ${{ runner.os }}-${{ steps.rust-install.outputs.cachekey }}-check

      - name: Install rust
        id: rust-install
        uses: dtolnay/rust-toolchain@stable

      - name: Check Formatting
        run: |
          cargo +${{ steps.rust-install.outputs.name }} fmt --check

      - name: Check with Clippy
        run: |
          cargo +${{ steps.rust-install.outputs.name }} clippy -- -D warnings

  test:
    strategy:
      matrix:
        rust-toolchain:
          - stable
          - nightly
        os:
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
            ~/.rustup
            target/
          key: ${{ runner.os }}-${{ steps.rust-install.outputs.cachekey }}-test

      - name: Install rust
        id: rust-install
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust-toolchain }}

      - name: Test
        run: |
          cargo +${{ steps.rust-install.outputs.name }} test

  actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install action-validator with asdf
        uses: asdf-vm/actions/install@v2
        with:
          tool_versions: |
            action-validator 0.5.1

      - name: Lint Actions
        run: |
          find .github/workflows -type f \( -iname \*.yaml -o -iname \*.yml \) \
            | xargs -I {} action-validator --verbose {}
