name: Upload release artifacts

on:
  release:
    types: [created]

jobs:
  crate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
            ~/.rustup
            target/
          key: ${{ runner.os }}-${{ steps.rust-install.outputs.cachekey }}-crate-release

      - name: Install rust
        id: rust-install
        uses: dtolnay/rust-toolchain@stable

      - name: Set version and Publish
        shell: bash
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
          RELEASE_TAG: ${{ github.ref }}
        run: |
          for crate in service-skeleton_derive service-skeleton; do
            mv $crate/Cargo.toml $crate/Cargo.toml.orig
            sed "s/0\\.0\\.0-git/${RELEASE_TAG##*\/v}/" $crate/Cargo.toml.orig >$crate/Cargo.toml
            cargo publish -p $crate --allow-dirty
          done

