name: Upload release artifacts

on:
  release:
    types: [created]

jobs:
  crate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo
            ~/.rustup
            target/
          key: ${{ runner.os }}-${{ steps.rust-install.outputs.cachekey }}-crate-release

      - name: Install rust
        id: rust-install
        uses: dtolnay/rust-toolchain@stable

      - name: Set version and Publish
        shell: bash
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
          RELEASE_TAG: ${{ github.ref }}
        run: |
          mv Cargo.toml Cargo.toml.orig
          sed "s/0\\.0\\.0-git/${RELEASE_TAG##*\/v}/" Cargo.toml.orig >Cargo.toml
          for crate in sscrypt service-skeleton_derive service-skeleton; do
            cargo publish -p $crate --allow-dirty --no-verify
          done

